<?php
/**
 * @Author : a.zinovyev
 * @Package: rsync
 * @License: http://www.opensource.org/licenses/mit-license.php
 */

namespace xobotyi\rsync;


class Option
{
    public const ACLS                = 'acls';
    public const ADDRESS             = 'address';
    public const APPEND              = 'append';
    public const APPEND_VERIFY       = 'append-verify';
    public const ARCHIVE             = 'archive';
    public const BACKUP              = 'backup';
    public const BACKUP_DIR          = 'backup-dir';
    public const BLOCKING_IO         = 'blocking-io';
    public const BLOCK_SIZE          = 'block-size';
    public const BWLIMIT             = 'bwlimit';
    public const CHECKSUM            = 'checksum';
    public const CHMOD               = 'chmod';
    public const COMPARE_DEST        = 'compare-dest';
    public const COMPRESS            = 'compress';
    public const COMPRESS_LEVEL      = 'compress-level';
    public const CONTIMEOUT          = 'contimeout';
    public const COPY_DEST           = 'copy-dest';
    public const COPY_DEVICES        = 'copy-devices';
    public const COPY_DIRLINKS       = 'copy-dirlinks';
    public const COPY_LINKS          = 'copy-links';
    public const COPY_UNSAFE_LINKS   = 'copy-unsafe-links';
    public const CVS_EXCLUDE         = 'cvs-exclude';
    public const DEL                 = 'del';
    public const DELAY_UPDATES       = 'delay-updates';
    public const DELETE              = 'delete';
    public const DELETE_AFTER        = 'delete-after';
    public const DELETE_BEFORE       = 'delete-before';
    public const DELETE_DELAY        = 'delete-delay';
    public const DELETE_DURING       = 'delete-during';
    public const DELETE_EXCLUDED     = 'delete-excluded';
    public const DEVICES             = 'devices';
    public const DIRS                = 'dirs';
    public const DRY_RUN             = 'dry-run';
    public const EXCLUDE             = 'exclude';
    public const EXCLUDE_FROM        = 'exclude-from';
    public const EXECUTABILITY       = 'executability';
    public const EXISTING            = 'existing';
    public const FAKE_SUPER          = 'fake-super';
    public const FILES_FROM          = 'files-from';
    public const FILTER              = 'filter';
    public const FORCE               = 'force';
    public const FROM0               = 'from0';
    public const FUZZY               = 'fuzzy';
    public const GROUP               = 'group';
    public const HARD_LINKS          = 'hard-links';
    public const HELP                = 'help';
    public const HUMAN_READABLE      = 'human-readable';
    public const ICONV               = 'iconv';
    public const IGNORE_ERRORS       = 'ignore-errors';
    public const IGNORE_EXISTING     = 'ignore-existing';
    public const IGNORE_TIMES        = 'ignore-times';
    public const INCLUDE             = 'include';
    public const INCLUDE_FROM        = 'include-from';
    public const INPLACE             = 'inplace';
    public const IPV4                = 'ipv4';
    public const IPV6                = 'ipv6';
    public const ITEMIZE_CHANGES     = 'itemize-changes';
    public const KEEP_DIRLINKS       = 'keep-dirlinks';
    public const LINKS               = 'links';
    public const LINK_DEST           = 'link-dest';
    public const LIST_ONLY           = 'list-only';
    public const LOG_FILE            = 'log-file';
    public const LOG_FILE_FORMAT     = 'log-file-format';
    public const MAX_DELETE          = 'max-delete';
    public const MAX_SIZE            = 'max-size';
    public const MIN_SIZE            = 'min-size';
    public const MODIFY_WINDOW       = 'modify-window';
    public const NO_IMPLIED_DIRS     = 'no-implied-dirs';
    public const NO_MOTD             = 'no-motd';
    public const NO_OPTION           = 'no-OPTION';
    public const NUMERIC_IDS         = 'numeric-ids';
    public const OMIT_DIR_TIMES      = 'omit-dir-times';
    public const ONE_FILE_SYSTEM     = 'one-file-system';
    public const ONLY_WRITE_BATCH    = 'only-write-batch';
    public const OUTPUT_8_BIT        = '8-bit-output';
    public const OUT_FORMAT          = 'out-format';
    public const OWNER               = 'owner';
    public const PARTIAL             = 'partial';
    public const PARTIAL_DIR         = 'partial-dir';
    public const PASSWORD_FILE       = 'password-file';
    public const PERMS               = 'perms';
    public const PORT                = 'port';
    public const PROGRESS            = 'progress';
    public const PROTECT_ARGS        = 'protect-args';
    public const PROTOCOL            = 'protocol';
    public const PRUNE_EMPTY_DIRS    = 'prune-empty-dirs';
    public const QUIET               = 'quiet';
    public const READ_BATCH          = 'read-batch';
    public const RECURSIVE           = 'recursive';
    public const RELATIVE            = 'relative';
    public const REMOVE_SOURCE_FILES = 'remove-source-files';
    public const RSH                 = 'rsh';
    public const RSYNC_PATH          = 'rsync-path';
    public const SAFE_LINKS          = 'safe-links';
    public const SIZE_ONLY           = 'size-only';
    public const SKIP_COMPRESS       = 'skip-compress';
    public const SOCKOPTS            = 'sockopts';
    public const SPARSE              = 'sparse';
    public const SPECIALS            = 'specials';
    public const STATS               = 'stats';
    public const SUFFIX              = 'suffix';
    public const SUPER               = 'super';
    public const TEMP_DIR            = 'temp-dir';
    public const TIMEOUT             = 'timeout';
    public const TIMES               = 'times';
    public const UPDATE              = 'update';
    public const VERBOSE             = 'verbose';
    public const VERSION             = 'version';
    public const WHOLE_FILE          = 'whole-file';
    public const WRITE_BATCH         = 'write-batch';
    public const XATTRS              = 'xattrs';

    private const OPTIONS_LIST = [
        self::ACLS                => 'acls',
        self::ADDRESS             => 'address',
        self::APPEND              => 'append',
        self::APPEND_VERIFY       => 'append-verify',
        self::ARCHIVE             => 'archive',
        self::BACKUP              => 'backup',
        self::BACKUP_DIR          => 'backup-dir',
        self::BLOCKING_IO         => 'blocking-io',
        self::BLOCK_SIZE          => 'block-size',
        self::BWLIMIT             => 'bwlimit',
        self::CHECKSUM            => 'checksum',
        self::CHMOD               => 'chmod',
        self::COMPARE_DEST        => 'compare-dest',
        self::COMPRESS            => 'compress',
        self::COMPRESS_LEVEL      => 'compress-level',
        self::CONTIMEOUT          => 'contimeout',
        self::COPY_DEST           => 'copy-dest',
        self::COPY_DEVICES        => 'copy-devices',
        self::COPY_DIRLINKS       => 'copy-dirlinks',
        self::COPY_LINKS          => 'copy-links',
        self::COPY_UNSAFE_LINKS   => 'copy-unsafe-links',
        self::CVS_EXCLUDE         => 'cvs-exclude',
        self::DEL                 => 'del',
        self::DELAY_UPDATES       => 'delay-updates',
        self::DELETE              => 'delete',
        self::DELETE_AFTER        => 'delete-after',
        self::DELETE_BEFORE       => 'delete-before',
        self::DELETE_DELAY        => 'delete-delay',
        self::DELETE_DURING       => 'delete-during',
        self::DELETE_EXCLUDED     => 'delete-excluded',
        self::DEVICES             => 'devices',
        self::DIRS                => 'dirs',
        self::DRY_RUN             => 'dry-run',
        self::EXCLUDE             => 'exclude',
        self::EXCLUDE_FROM        => 'exclude-from',
        self::EXECUTABILITY       => 'executability',
        self::EXISTING            => 'existing',
        self::FAKE_SUPER          => 'fake-super',
        self::FILES_FROM          => 'files-from',
        self::FILTER              => 'filter',
        self::FORCE               => 'force',
        self::FROM0               => 'from0',
        self::FUZZY               => 'fuzzy',
        self::GROUP               => 'group',
        self::HARD_LINKS          => 'hard-links',
        self::HELP                => 'help',
        self::HUMAN_READABLE      => 'human-readable',
        self::ICONV               => 'iconv',
        self::IGNORE_ERRORS       => 'ignore-errors',
        self::IGNORE_EXISTING     => 'ignore-existing',
        self::IGNORE_TIMES        => 'ignore-times',
        self::INCLUDE             => 'include',
        self::INCLUDE_FROM        => 'include-from',
        self::INPLACE             => 'inplace',
        self::IPV4                => 'ipv4',
        self::IPV6                => 'ipv6',
        self::ITEMIZE_CHANGES     => 'itemize-changes',
        self::KEEP_DIRLINKS       => 'keep-dirlinks',
        self::LINKS               => 'links',
        self::LINK_DEST           => 'link-dest',
        self::LIST_ONLY           => 'list-only',
        self::LOG_FILE            => 'log-file',
        self::LOG_FILE_FORMAT     => 'log-file-format',
        self::MAX_DELETE          => 'max-delete',
        self::MAX_SIZE            => 'max-size',
        self::MIN_SIZE            => 'min-size',
        self::MODIFY_WINDOW       => 'modify-window',
        self::NO_IMPLIED_DIRS     => 'no-implied-dirs',
        self::NO_MOTD             => 'no-motd',
        self::NO_OPTION           => 'no-OPTION',
        self::NUMERIC_IDS         => 'numeric-ids',
        self::OMIT_DIR_TIMES      => 'omit-dir-times',
        self::ONE_FILE_SYSTEM     => 'one-file-system',
        self::ONLY_WRITE_BATCH    => 'only-write-batch',
        self::OUTPUT_8_BIT        => '8-bit-output',
        self::OUT_FORMAT          => 'out-format',
        self::OWNER               => 'owner',
        self::PARTIAL             => 'partial',
        self::PARTIAL_DIR         => 'partial-dir',
        self::PASSWORD_FILE       => 'password-file',
        self::PERMS               => 'perms',
        self::PORT                => 'port',
        self::PROGRESS            => 'progress',
        self::PROTECT_ARGS        => 'protect-args',
        self::PROTOCOL            => 'protocol',
        self::PRUNE_EMPTY_DIRS    => 'prune-empty-dirs',
        self::QUIET               => 'quiet',
        self::READ_BATCH          => 'read-batch',
        self::RECURSIVE           => 'recursive',
        self::RELATIVE            => 'relative',
        self::REMOVE_SOURCE_FILES => 'remove-source-files',
        self::RSH                 => 'rsh',
        self::RSYNC_PATH          => 'rsync-path',
        self::SAFE_LINKS          => 'safe-links',
        self::SIZE_ONLY           => 'size-only',
        self::SKIP_COMPRESS       => 'skip-compress',
        self::SOCKOPTS            => 'sockopts',
        self::SPARSE              => 'sparse',
        self::SPECIALS            => 'specials',
        self::STATS               => 'stats',
        self::SUFFIX              => 'suffix',
        self::SUPER               => 'super',
        self::TEMP_DIR            => 'temp-dir',
        self::TIMEOUT             => 'timeout',
        self::TIMES               => 'times',
        self::UPDATE              => 'update',
        self::VERBOSE             => 'verbose',
        self::VERSION             => 'version',
        self::WHOLE_FILE          => 'whole-file',
        self::WRITE_BATCH         => 'write-batch',
        self::XATTRS              => 'xattrs',
    ];

    public static function IsSupported(string $option) :bool {
        return (bool)(self::OPTIONS_LIST[$option] ?? false);
    }
}